### ISSUE TITLE
FIMatrix in Rules contains itemsets of length 0

### ISSUE THREAD

**Issue by abuchmueller** [TimToebrock/Project_Apriori#9]
```
library(ProjectApriori)
data("Groceries")
frequent_items <- FindFrequentItemsets(Groceries, 0.01)
Rules <- AssociationRules(Itemsets=Groceries, minsupport = 0.01, 
                          minconfidence = 0.4, arefrequent = FALSE)
```

`colSums(Rules@FrequentItemsets)`
Rules contains 4 columns with no TRUE value

FindFrequentItemsets however returns only itemsets of length >= 1 (as intended)
`colSums(frequent_items)`

**Comment by titoeb** [comment]
fixed.

Both issue 9 and 10 came from the fact that I use the FrequentItems slot iternally for the creation of the rules. I remove Items that are not relevant for the Rule generation hence changin the FrequentItemset object. This leads obviously to nonsensical Frequentitems. Since I think it is useful to have the frequent Items in the rule object I now save them in the beginning of Association rules and then overwrite the "wrong" Frequentitemset before outputing the rules.

Nevertheless, really nice that you found that issue!
